# Terraform Format
- name: Terraform Format
  run: terraform fmt -check -recursive

# Setup TFLint
- name: Setup TFLint
  uses: terraform-linters/setup-tflint@v6

# Initialize TFLint
- name: Initialize TFLint
  run: tflint --init

# Run TFLint
- name: Run TFLint
  run: tflint --recursive

# Terraform Init
- name: Terraform Init
  run: terraform init

# Terraform Validate
- name: Terraform Validate
  run: terraform validate

# tfsec Scan
- name: Run tfsec
  uses: aquasecurity/tfsec-action@v1

# Checkov Scan
- name: Run Checkov
  uses: bridgecrewio/checkov-action@master
  with:
    directory: .

# Trivy IaC Scan
- name: Run Trivy
  uses: aquasecurity/trivy-action@master
  with:
    scan-type: config
    scan-ref: .

# SonarQube Scan
- name: SonarQube Scan
  uses: SonarSource/sonarqube-scan-action@v5
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

# Terraform Plan
- name: Terraform Plan
  run: terraform plan -input=false

# Terraform Apply
- name: Terraform Apply
  if: github.ref == 'refs/heads/Main' && github.event_name == 'push'
  run: terraform apply -auto-approve -input=false
